[config]

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.json]
input_path = './templates/colors.json'
output_path = '~/.config/luna/colors/colors.json'

[templates.overview]
input_path = './templates/overview.txt'
output_path = './overview.txt'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'
