"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color6)\
${custom.moon}\
[](color6)\
[●](color1)\
[](color6)\
[‎ ](bg:color6)\
$directory\
[\n](color6)\
$character\
"""

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '{{colors.primary.default.hex}}'
color2 = '{{colors.primary_container.default.hex}}'
color3 = '{{colors.on_secondary_container.default.hex}}'
color4 = '{{colors.error.default.hex}}'
color5 = '{{colors.primary_fixed.default.hex}}'
color6 = '{{colors.inverse_primary.default.hex}}'
color7 = '{{colors.primary_fixed_dim.default.hex}}'
color8 = '{{colors.on_primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[character]
success_symbol = "[● ](color1)"
error_symbol = "[● ](color1)[](color4)"

[custom.moon]
command = "starship-moon"
when = true
shell = "bash"
style = "bg:color6 fg:color1"

[directory]
style = "bg:color6 fg:color1"
read_only = ""
format = '[$path]($style)'
