[config]

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.quickshell]
input_path = './templates/qml-colors.qml'
output_path = '~/.config/quickshell/Colors.qml'

[templates.overview]
input_path = './templates/overview.txt'
output_path = './overview.txt'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'
